// ===----------------------------------------------------------------------===
//
// This source file is part of the Hummingbird DocC Middleware open source project
//
// Copyright (c) 2025 Röck+Cöde VoF. and the Hummingbird DocC Middleware project authors
// Licensed under the EUPL 1.2 or later.
//
// See LICENSE for license information
// See CONTRIBUTORS for the list of Hummingbird DocC Middleware project authors
//
// ===----------------------------------------------------------------------===

/// An enumeration that represents the documentation folders that could be generated by the `DocC` building process.
enum DocumentationFolder: String, CaseIterable {
    /// An article document, which can also be used for (source code generated) technical documentation as well.
    case article = "documentation"
    /// A tutorial document.
    case tutorial = "tutorials"
}

// MARK: - Pathable

extension DocumentationFolder: Pathable {
    
    // MARK: Computed
    
    var path: String {
        .init(format: .Format.Path.root, rawValue)
    }
    
}
