// ===----------------------------------------------------------------------===
//
// This source file is part of the Hummingbird DocC Middleware open source project
//
// Copyright (c) 2025 Röck+Cöde VoF. and the Hummingbird DocC Middleware project authors
// Licensed under the EUPL 1.2 or later.
//
// See LICENSE for license information
// See CONTRIBUTORS for the list of Hummingbird DocC Middleware project authors
//
// ===----------------------------------------------------------------------===

/// An enumeration that represents all possible asset folders that could be generated by the `DocC` building process.
enum AssetFolder: String, CaseIterable {
    /// A folder that contains all CSS style sheets.
    case css
    /// A folder that contains all documentation data.
    case data
    /// A folder that contains all other resources.
    case downloads
    /// A folder that contains all image resources.
    case images
    /// A folder that contains all image resources.
    case img
    /// A folder that contains all generated `HTML` code.
    case index
    /// A folder that contains all generated `Javascript` code.
    case js
    /// A folder that contains all video resources.
    case videos
}

// MARK: - Pathable

extension AssetFolder: Pathable {
    
    // MARK: Computed
    
    var path: String {
        .init(format: .Format.Path.folder, rawValue)
    }
    
}
