// ===----------------------------------------------------------------------===
// 
// This source file is part of the Hummingbird DocC open source project
// 
// Copyright (c) 2025 Röck+Cöde VoF. and the Hummingbird DocC project authors
// Licensed under Apache license v2.0
// 
// See LICENSE for license information
// See CONTRIBUTORS for the list of Hummingbird DocC project authors
//
// SPDX-License-Identifier: Apache-2.0
// 
// ===----------------------------------------------------------------------===

/// An enumeration that represents the documentation folders that could be generated by the `DocC` building process.
enum DocumentationFolder: String, CaseIterable {
    /// An article document, which can also be used for (source code generated) technical documentation as well.
    case article = "documentation"
    /// A tutorial document.
    case tutorial = "tutorials"
}

// MARK: - Pathable

extension DocumentationFolder: Pathable {
    
    // MARK: Computed
    
    var path: String {
        .init(format: .Format.Path.root, rawValue)
    }
    
}
